---
extends: default

rules:
  comments:
    min-spaces-from-content: 1
  comments-indentation: disable
  document-start: disable
  indentation:
    indent-sequences: consistent
  line-length: disable
  truthy:
    check-keys: false
    allowed-values: ["true", "false", "yes", "no", "on", "off"]

ignore:
  - .git/
  - talos/
  - "**/*.sops.yaml"
  - "**/*.sops.yml"
